### ISSUE TITLE
Error when deploying of the ONOS RIC

### ISSUE THREAD

**Issue by RogelioPumajulca** [5GSEC/5G-Spector#2]
Hello guys,
here I leave an issue that I have found (until now) when deploying the ONOS RIC in the VM artifact, I hope you can review it and maybe confirm if the applied workaround is enough or it may need further configurations.
Thanks.!

**After running:**
`make OPT=ric`

**I got the following error:**
`Error: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "kpimon" namespace: "" from "": no matches for kind "Entity" in version "topo.onosproject.org/v1beta1"`

![ONOS-RIC_Error](https://github.com/5GSEC/5G-Spector/assets/21093895/dae789de-e0dd-4020-a366-cd71b37cfe3b)

**Workaround:**
```
helm repo add onosproject https://charts.onosproject.org
helm repo update
helm install -n kube-system onos-operator onosproject/onos-operator --wait

```

**Comment by onehouwong** [comment]
Thank you so much for sharing! I have added your workaround to the troubleshooting section of the [deployment guide](https://github.com/5GSEC/5G-Spector/wiki/5G%E2%80%90Spector-Artifact-in-a-Simulated-LTE-Network#onos-ric-deployment-error) so that everyone deploying the ONOS RIC can benefit from it!
