### ISSUE TITLE
All the containers for the pods mobi-expert-xapp & onos-a1t are not getting ready.

### ISSUE THREAD

**Issue by geekkypyconda** [5GSEC/5G-Spector#8]
So I am trying to setup the 5G-Spector from scratch using this repo: https://github.com/5GSEC/5G-Spector/wiki/Build-5G%E2%80%90Spector-from-scratch-in-an-OAI-5G-network#iii-deploy-a-5g-network-w-rf-simulation-from-scratch

I am trying it out in a Virtual Box VM:
VM Specs:
* OS -> Ubuntu Server 20.04 LTS
* RAM -> 12GB
* CPUs -> 6x Intel Xeon E5 1650 cores @4.0 Ghz
* Storage -> 250 GB HDD

Now when I tried deploying the mobieXpert xApp then all the containers of **mobi-expert-xapp** & **onos-a1t** are not getting in the ready state.
![image](https://github.com/user-attachments/assets/d54bff5c-e388-4e4f-b311-847f073dc1b9)

When i tried to describe the pods then i am getting **Startup probe failed** error.
Below is the screenshot for **mobi-expert-xapp**
![image](https://github.com/user-attachments/assets/9dd4dac7-67b4-4d02-9d30-dfb789e09d8c)

Below is the screenshot for **onos-a1t**
![image](https://github.com/user-attachments/assets/5bf84bf3-a1a1-4607-8b35-a1b67f0fb1d9)

I also tried to curl on the IP address of the services but I was getting connection refused error there also.

Below is the snapshot of the services
![image](https://github.com/user-attachments/assets/0cfbae5c-cf6f-4163-b861-e3eb4bc7bc51)

Below is the snapshot of the curl commands that I tried to execute
![image](https://github.com/user-attachments/assets/73ef58f9-9991-4eb3-a07d-1dab12d37281)

**Comment by onehouwong** [comment]
The failure of the `onos-a1t` container shall be fine as it handles the A1 interface of the nRT-RIC. You can delete this pod through `helm` if you don't want to see the errors.

The current `mobi-expert-xapp` error is due to a bug that we find (possibly in the ONOS python SDK) which triggers an RPC error on the MobieXpert xApp. The way to get all the stuffs running would be: deploy MobiFlow Auditor -> deploy MobieXpert -> deploy gNB -> run attack.
 
Because of the aforementioned bug, the MobieXpert will soon crash after it receives the data through RPC. If that occurs you will have to restart the setup, i.e., the Mobiflow Auditor and MobieXpert xApps over again.
